defaults:
  - job_logging: disabled

# configure world
num_agents: 1
num_landmarks: 1

# configure map
SIZE_X: 7
SIZE_Y: 7

# configure agent
hidden: 16
gamma: 0.99
learning_rate: 1e-3
betas: [0.9, 0.999]
eps: 1e-8

# configure training
max_epochs: 10000
max_episode_length: 20
batch_size: 64
populate_steps: 1000
capacity: 1000000
decay_epochs: 2000
synch_epochs: 10000

# configure logs
logs_on_termial: False