defaults:
  - job_logging: disabled

# configure world
num_agents: 2
num_landmarks: 2

# configure map
SIZE_X: 9
SIZE_Y: 9

# configure agent
hidden1: 32
hidden2: 32
gamma: 0.99
tau: 0.001
learning_rate: 1e-3
beta1: 0.9
beta2: 0.999
eps: 1e-8

# configure training
max_epochs: 20000
max_episode_length: 20
batch_size: 64
populate_steps: 1000
capacity: 1000000
decay_epochs: 3000

# configure logs
logs_on_termial: False