defaults:
  - opt: rmsprop
  - job_logging: disabled

# configure world
num_agents: 8 #8
num_landmarks: 40 #40

# configure agent
visible_range: 7
hidden1: 32
hidden2: 64
hidden3: 128
gamma: 0.9

phase: 'validate'
     # 'training'
     # 'validate'

# configure training
max_epochs: 20000
max_episode_length: 200
batch_size: 32
populate_steps: 1000
capacity: 100000
epsilon_decay: 0.9998
epsilon_initial: 1.0
epsilon_end: 0.05

# configre validate
validate_epochs: 1000
load_weight: True
model_path: '/home/motokawa/projects/EXP/outputs/2020-12-02/exp7/'
